### DISCUSSION TITLE
What should Flock use for branch names?

### DISCUSSION THREAD

**Discussion by matthew-carroll** [join-the-flock/nest#20] [Q&A]
We're assembling GitHub workflows to rebase Flock with the latest changes from Flutter. As we setup this rebasing behavior, it begs the question, what branch names should we use for Flock?

Flock can use the same branch names as Flutter, e.g., `master`, `beta`, `stable`. Or, flock can preserve the existing Flutter history on the standard branches and then publish Flock versions of each branch, e.g., `flock-master`, `flock-beta`, `flock-stable`.

There's a similar question for release tags, e.g., `3.24.5` vs `flock-3.24.5`.

What are your thoughts? Do you have tooling that would be broken if we went one way or the other?

**Comment by jezell** [comment]
Things to consider:

If you already have a flutter fork, I believe you can't make a second one under the same owner. So if you want to have both flock and flutter code in the same internal repo, and the ability to switch back and forth, reusing the same names could make it hard to switch between official and release channels without maintaining two seperate repos, one of which can't be designated as a fork of flutter in github.

FVM does support pulling specific tags / branches / hashes, so I believe FVM is ok regardless of the approach.

Not sure about how we are going to integrate with things like CodeMagic, but might be worth putting together some guidance and samples there to make sure whatever we do doesn't cause any problems for people using popular Flutter CI platforms. Probably a good idea anyway since that's going to quickly become a concern as soon as anyone moves from dev to deploy regardless.

**Comment by ChrisZou** [comment]
I believe the intuitive approach should prevail. This means that if you are in Flock, `master` (or `beta`, `stable`) should refer to Flock’s respective branches. If there’s a need to preserve the existing Flutter history, the branch name should explicitly be `flutter-master` to indicate Flutter’s master branch.

**Reply by jezell** [reply]
Would you prefer that you had both a flock and a flutter repo in your organization or personal account, rather than them sharing the same repo?

**Reply by ChrisZou** [reply]
I personally prefer the formal(different repos), and with FVM to switch between them.

**Comment by fonkamloic** [comment]
I have two questions and a recommendation. 

Managing Flock locally would be straightforward. However, the main challenge, in my opinion, would be the necessary refactoring of cicd_workflows to potentially switch from the official version to Flock dynamically.

Question; Locally
1- Is it possible for you to script the symbolic link creation for Flock. The same way sidekick use to map global fvm flutter to the default flutter? 
If this is possible, I would recommend keeping the same name as flutter branches. And make a feature request to modify sidekick to switch 

![Screenshot 2024-11-23 at 3 56 16 PM](https://github.com/user-attachments/assets/c47ca5ca-1ec1-42c0-9a9a-003ec1e8fa27)

In the fvm, have a separate folder for Flock version with the same branch names. 

![image](https://github.com/user-attachments/assets/9c563974-a6f1-498d-b21c-ffb2a7334e56)

Question; For Pipelines 
2- Will you host a CDN for flutter precompile optimized binaries and create a tool like `subosito/flutter-action@v2` to fecht? 
If you are considering having developers point their workflow to download directly from GitHub, it might be cost-prohibitive because it will increase build time.

At the end of the day, I believe it would be easier to adopt Flock if it only requires changing one line in your workflow—specifically, you just need to specify where to fetch Flutter, without worrying about which branch to use. To illustrate, it's like being able to change the base URL of a request without having to consider whether the exposed endpoints are different.

Let's say for instance this is my workflow 
```

name: Flutter Build with Fork or Official Version

on:
  workflow_dispatch:
    inputs:
      flutter_source:
        description: "Choose Flutter source: fork or official"
        required: true
        default: "official"
      flutter_version:
        description: "Specify the Flutter version or branch to use"
        required: true
        default: "latest-stable"

env:
  FLUTTER_VERSION: ${{ github.event.inputs.flutter_version }}

jobs:
  flutter-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Decide Flutter Source
      - name: Set Flutter Source
        id: flutter-source
        run: |
          if [[ "${{ github.event.inputs.flutter_source }}" == "fork" ]]; then
            echo "USE_FORK=true" >> $GITHUB_ENV
          else
            echo "USE_FORK=false" >> $GITHUB_ENV
          fi

      # Step 3A: Use Flutter Fork (if selected)
      - name: Setup Flutter Fork
        if: env.USE_FORK == 'true'
        run: |
          echo "Cloning Flutter Fork with version/branch: $FLUTTER_VERSION"
          git clone --branch $FLUTTER_VERSION https://github.com/your-username/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          flutter doctor
    
     # Step 3B: Use Official Flutter (if selected)
      - name: Setup Official Flutter
        if: env.USE_FORK == 'false'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Step 4: Install Dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Step 5: Build the App
      - name: Build APK
        run: flutter build apk --release

      # Step 6 (Optional): Archive Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk


```

Having a tool like flutter-action to manage step 3A would be beneficial; otherwise, the logic could become confusing, especially with larger projects, various flavors, and white-labeled apps that have different Flutter version dependencies.
